# Generated by Django 3.2.16 on 2023-11-13 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(max_length=100)),
                ('nombre_de_personne', models.IntegerField()),
                ('info', models.TextField()),
                ('prix', models.IntegerField()),
                ('nombre_de_place_restant', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_allocateur', models.CharField(max_length=100)),
                ('prenom_allocateur', models.CharField(max_length=100)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.maison')),
            ],
        ),
    ]
