# Generated by Django 3.2.16 on 2023-11-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20231116_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='nombre_de_chambre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_personne', models.IntegerField()),
                ('info', models.TextField()),
                ('prix', models.IntegerField()),
                ('nombre_de_place_restant', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.maison')),
            ],
        ),
    ]
