# Generated by Django 3.2.16 on 2023-11-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20231126_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='nombre_de_chambre_inscrit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
